# Generated by Django 5.2 on 2025-05-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
