# Generated by Django 5.2 on 2025-05-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
